### ISSUE TITLE
is google drive working?

### ISSUE THREAD

**Issue by Saifallak** [thitlwincoder/direct_link#4]
i was trying with link 

https://drive.google.com/file/d/1dHmVk7XWR8Z4-Xsb5824iPv_9AIS1Zih

and also

https://drive.google.com/get_video_info?docid=1dHmVk7XWR8Z4-Xsb5824iPv_9AIS1Zih

```
Unhandled exception:
Null check operator used on a null value
#0      Gdrive (package:direct_link/sites/gdrive.dart:10:22)
<asynchronous suspension>
#1      main (file:///C:/Users/Saifallak/IdeaProjects/direct_link/example/direct_link_example.dart:4:15)
<asynchronous suspension>
```

**Comment by thitlwincoder** [comment]
Not available at this time. I will fix it again.
